name: Build and deploy

on:
  push:
    branches:
    - main

# Limit concurrent workflow execution to 1.
# Running jobs will be canceled in case a new workflow is started.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  APP_IMAGE: ghcr.io/${{ github.repository_owner }}/tanzu-devslam-spring:${{ github.run_number }}
  JAVA_VERSION: 17

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}
        cache: maven
    - name: Test app
      run: cd app && ./mvnw -B test

  deploy-image:
    needs:
    - test-app
    runs-on: ubuntu-latest
    steps:
      - uses: buildpacks/github-actions/setup-pack@v4.4.0
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        # Note: make sure the container image name is lowercase only.
        run: cd app && ./mvnw -B spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$(echo $APP_IMAGE | awk '{print tolower($0)}') -Dspring-boot.build-image.publish=true
        env:
          # We need to set these properties when using GitHub Actions,
          # so that Spring Boot can publish the resulting image to GHCR.
          DOCKER_PUBLISH_USERNAME: ${{ github.actor }}
          DOCKER_PUBLISH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
